server:
  port: 8080
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---
spring:
  profiles:
    active: dev
  h2.console.enabled: true
  datasource:
    platform: h2
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
    properties.hibernate.format_sql: true
logging:
  level:
    com.blog: DEBUG
---